### ISSUE TITLE
CI setup to ensure changes don't break existing tests

### ISSUE THREAD

**Issue by lsm5** [QUBIP/pq-container#5]
We currently don't have test.sh running in upstream CI so it's hard to tell if any upstream changes will break existing tests.

Not certain if the public instance of konflux is fully mature for this yet, but we can do this with packit and testing-farm. 

Plan for CI:
1. Add [packit service](https://packit.dev/docs/guide) to the QUBIP org and enable packit access to the pq-container repo. Should be done by someone with org-level access IIUC.

3. Add packit config with a basic TMT test. The test could look similar to what's been added in [Fedora dist-git](https://src.fedoraproject.org/rpms/openssl/pull-request/62#request_diff)

PTAL @sahanaprasad07

**Comment by lsm5** [comment]
I'm also checking on the latest in konflux in case it can help here.

**Comment by sahanaprasad07** [comment]
I've set up packit for the QUBIP repo - see https://github.com/organizations/QUBIP/settings/installations/57972250

**Comment by lsm5** [comment]
packit's now working on #9 .
